name: "Release Please"

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Update Release PR
        id: release
        # v4.1.3
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          token: ${{ secrets.JEKYLLBOT_TOKEN }}
